# Generated by Django 5.1.13 on 2025-11-02 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(choices=[('BBVA', 'BBVA'), ('Santander', 'Santander'), ('CaixaBank', 'CaixaBank'), ('Bankia', 'Bankia'), ('Sabadell', 'Sabadell')], default='BBVA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('banco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_banco', to='examen_AntonioR.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca_movil', to='examen_AntonioR.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Votaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_votacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen_AntonioR.cliente')),
                ('movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen_AntonioR.movil')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='votaciones_movil',
            field=models.ManyToManyField(related_name='cliente_votaciones', through='examen_AntonioR.Votaciones', to='examen_AntonioR.movil'),
        ),
    ]
