# Generated by Django 5.1.13 on 2025-11-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_AntonioR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='votaciones_movil',
            field=models.ManyToManyField(blank=True, null=True, related_name='cliente_votaciones', through='examen_AntonioR.Votaciones', to='examen_AntonioR.movil'),
        ),
    ]
