# Generated by Django 5.1.13 on 2025-11-04 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_AntonioR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha_lanzamiento',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='genero',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='ventas_estimadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('review', models.TextField()),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_videojuego', to='examen_AntonioR.videojuego')),
            ],
        ),
    ]
