# Generated by Django 5.1.13 on 2025-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_AntonioR', '0002_remove_estudio_pais_remove_sede_numero_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='fabricante',
            field=models.CharField(choices=[('Sony', 'Sony'), ('Microsoft', 'Microsoft'), ('Nintendo', 'Nintendo'), ('PC', 'PC'), ('Apple', 'Apple')], default='Estados Unidos', max_length=50),
        ),
    ]
