# Generated by Django 5.1.13 on 2025-11-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_AntonioR', '0003_plataforma_fabricante'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='anyo_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
